print("hello qwfdqwfdc")
print("hello qwfdqwfdqw")
print("hello rfdeqwfd")
print("hello worfdeqwfdeld")
print("hello feqwfdeqw")
print("hello wofeqwfeqwrld")
print("hello qwfdqwf")
print("hello fwqfdqw")
